spring:
  profiles:
    active: local
#    active: dev

  cloud:
    config:
      name: popool

  config:
#    import: configserver:http://ec2-13-124-159-0.ap-northeast-2.compute.amazonaws.com:8888/
    import: optional:configserver:http://localhost:8888/