name: Java CI with Gradle

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-application:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x ./p-application/gradlew
        shell: bash

      - name: Build P-Application with Gradle
        run: ./p-application/gradlew clean :p-application:build --exclude-task test --warning-mode all
        shell: bash

      - name: Get current time
        uses: 1466587594/get-current-time@v2
        id: current-time
        with:
          format: YYYY-MM-DDTHH-mm-ss
          utcOffset: "+09:00"

      - name: Generate p-application package
        run: |
          mkdir -p p-application
          cp p-application/build/libs/*.jar p-application/application.jar
          cp Procfile p-application/Procfile
          cp -r .ebextensions p-application/.ebextensions
          cd p-application && zip -r p-application.zip .

#      #Gradle 를 사용해 프로젝트 빌드 수행
#      - name: Build with Gradle P-Appication
#        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
#        run: ./gradlew build -x test  #Test 는 Skip
#        with:
#          arguments: build

      #적용 했을 때 빌드 시간이 20~30% 가량 향상 (필수 X)
      - name: Gradle Caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-